# Generated by Django 6.1 on 2026-09-12 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_deliveryzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_zone',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='products.deliveryzone'),
            preserve_default=False,
        ),
    ]
