# Generated by Django 6.1 on 2026-09-15 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_payment_status'),
        ('subscriptions', '0002_subscription_delivery_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='delivery_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='products.deliveryzone'),
        ),
    ]
