# Generated by Django 6.1 on 2026-09-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscription_delivery_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='delivery_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='subscription',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CANCELLED', 'Cancelled')], default='PENDING_PAYMENT', max_length=20),
        ),
    ]
